---
title: "4_Forest_Plot"
author: "yuki"
date: "2023-12-05"
output: html_document
---
```{r}
metafor::forest(res[[1]])
```

```{r}
plot <- list()
```

```{r}
plot[[1]] <- df[[6]] %>%
  dplyr::arrange(unique_ID) %>%
  dplyr::mutate(Order = row_number()) %>%
  ggplot2::ggplot(., aes(x = yi , y = reorder(unique_ID, -Order))) +
  ggplot2::geom_vline(xintercept = 0, linetype = "solid", color = "grey20", linewidth = 0.5) +
  ggplot2::geom_vline(xintercept = -0.063, linetype = "dashed", color = "grey20", linewidth = 0.5) +
  ggplot2::geom_errorbar(aes(xmin = ci.lb, xmax = ci.ub), linewidth = 1, width = 0.3) +
  ggplot2::geom_point(shape =15, size = 5) +
  ggplot2::annotate("text", x = -0.9, y = 0, label = "Random Effect (n = 22)", hjust = 0, family='serif',fontface = "bold", size = 5) +
  ggplot2::annotate("text", x = 0.7, y = 0, label = "-0.063 (-0.111, -0.015)", hjust = 0.5, family='serif',fontface = "bold", size = 5) +
  ggplot2::annotate("text", x = -0.7, y = -1, label = "") +
  #ggplot2::geom_errorbar(aes(xmin = 0.16, xmax = 1.15, y = 0), color = "#6499E9", linewidth = 1, width = 0.1) + # Fixed Effect CI
  #ggplot2::geom_point(aes(x = 0.66, y = 0), color = "#6499E9", shape = 18, size = 12) + # Fixed Effect Point
  ggplot2::geom_polygon(
    data = data.frame(x = c(-0.1112, -0.063, -0.0147, -0.063), y = c(0, 0.20, 0, -0.20)),
    aes(x = x, y = y),
    fill = "#6499E9", color = "#6499E9"
  ) +
  ggplot2::geom_text(
    aes(x = -0.9, y = reorder(unique_ID, -Order), label = reorder(unique_ID, -Order)), hjust = 0, family='serif',size = 5
  ) + # Author_Year_Study
  ggplot2::geom_text(
    aes(x = 0.7, y = reorder(unique_ID, -Order), label = CI), hjust = 0.5, family='serif', size = 5
  ) + # Right: P-value
  ggplot2::scale_x_continuous(
    limits = c(-0.9, 0.8), 
    breaks = seq(-0.4,0.4, by = 0.1),
    sec.axis = sec_axis(
      ~., breaks = c(-0.75, 0.7),
      labels = c("Authors (Year) Study","CI")
    ),
  ) +
  ggplot2::labs(x = "") +
  #ggplot2::ggtitle("Forest Plot") +
  papaja::theme_apa() +
  ggplot2::theme(
    legend.position = "none",
    axis.line.x = element_line(linewidth = 1.5),
    axis.title.x = element_text(size = 15, family='serif', hjust = 0.55),
    axis.text.x= element_text(size = 20, family='serif', face = "bold"),
    plot.title = element_text(size = 20, family='serif', face = "bold", hjust = 0),
    legend.key.width = unit(2, "cm"),
    legend.key.height = unit(5, "cm"),
    legend.text = element_text(size = 20, family='serif'),
    legend.title = element_blank(),
    axis.line.y = element_blank(),
    axis.ticks.y= element_blank(),
    axis.ticks.x.top = element_blank(),
    axis.text.y= element_blank(),
    axis.title.y= element_blank(),
  ) 

names(plot)[1] <- "Forest Plot"

ggsave(plot[[1]], filename = "../PLOT/Forest_Plot.png", width = 12, height = 10, limitsize = FALSE)
```
