# Structural Equation Modeling
## Mediation
```{r Mediation SEM}
result.SEM.med <- capture.output({
  SEM.med <- 'ASC =~ ASC1 + ASC2 + ASC3 + ASC4 + ASC5
              OSC =~ OSC1 + OSC2 + OSC3 + OSC4 + OSC5 + OSC6
              SCO =~ ASC + OSC
              RD =~ RD1 + RD2 + RD3 + RD4 + RD5
              POS =~ POS1 + POS2 + POS3 + POS4 + POS5
              LS =~ LS1 + LS2 + LS3 + LS4 + LS5
              RD =~ SCO
              POS =~ SCO
              LS =~ RD + POS + SCO' %>%
  lavaan::sem(.,data=df.raw, estimator="ML") 
  lavaan::summary(SEM.med, fit.measures=TRUE, standardized=TRUE)
})

writeLines(result.SEM.med, "./OUTPUT/SEM/SEM.med.md")

rm(result.SEM.med)
```

```{r Mediation SEM Mplus}
SEM.med <- mplusObject(
   TITLE = "
    Mediation;
   ",
   ANALYSIS = "
    TYPE =general;
    bootstrap = 5000;
    process=16;
   ",
   MODEL = "  
    ASC by ASC1-ASC5;
    OSC by OSC1-OSC6;
    SCO by ASC@0.8 OSC@0.8;
    
    RD by RD1-RD5;
    POS by POS1-POS5;
    
    LS by LS1-LS5;
    
    RD on SCO(a1);
    POS on SCO(a2);
    LS on SCO(c)
          RD(b1)
          POS(b2);
   ",
   MODELCONSTRAINT = "
   NEW(IE_RD 
       IE_POS);
   
    IE_RD = a1*b1;
    IE_POS = a2*b2;
   ",
   OUTPUT = "
    CINT(bcbootstrap);
    STDYX",
   rdata = df.raw)

mplusModeler(SEM.med, modelout = "./OUTPUT/SEM/Mplus/SEM.med.inp", run = 1L)
rm(SEM.med)
```

## Moderation
### SCD as moderation
```{r Moderator is SCD, include=FALSE}
SEM.mod.SCD <- mplusObject(
   TITLE = "
    Moderator is SCD;
   ",
   ANALYSIS = "
    TYPE =general RANDOM;  
    estimator=MLR; 
    ALGORITHM=INTEGRATION;
    convergence=0.01;
   ",
   MODEL = "  
    ASC by ASC1-ASC5;
    OSC by OSC1-OSC6;
    SCO by ASC@0.8 OSC@0.8;
    
    SCD@1;
    OD | SCO XWITH SCD;
    
    RD by RD1-RD5;
    POS by POS1-POS5;
    
    LS by LS1-LS5;
    
    RD on SCO(a1)
          SCD
          OD(w1);
    POS on SCO(a2)
           SCD
           OD(w2);
    LS on SCO(c)
          RD(b1)
          POS(b2);
   ",
   MODELCONSTRAINT = "
   NEW(L_SCD M_SCD H_SCD
      IE_L_RD IE_M_RD IE_H_RD
      IE_L_POS IE_M_POS IE_H_POS
      
      DIF_LM_RD DIF_LH_RD DIF_MH_RD
      DIF_LM_POS DIF_LH_POS DIF_MH_POS
      );
   
    L_SCD = -1;
    M_SCD = 0;
    H_SCD = 1;
   
    IE_L_RD = (a1+w1*L_SCD)*b1;
    IE_M_RD = (a1+w1*M_SCD)*b1;
    IE_H_RD = (a1+w1*H_SCD)*b1;
   
    IE_L_POS = (a2+w2*L_SCD)*b2;
    IE_M_POS = (a2+w2*M_SCD)*b2;
    IE_H_POS = (a2+w2*H_SCD)*b2;
   
    DIF_LM_RD = IE_L_RD - IE_M_RD;
    DIF_LH_RD = IE_L_RD - IE_H_RD;
    DIF_MH_RD = IE_M_RD - IE_H_RD;
    
    DIF_LM_POS = IE_L_POS - IE_M_POS;
    DIF_LH_POS = IE_L_POS - IE_H_POS;
    DIF_MH_POS = IE_M_POS - IE_H_POS;
   
    PLOT(P_L_RD P_M_RD P_H_RD
         P_L_POS P_M_POS P_H_POS);
    LOOP(XVAL,1,7,0.1);
    P_L_RD = IE_L_RD*XVAL;
    P_M_RD = IE_M_RD*XVAL;
    P_H_RD = IE_H_RD*XVAL;
    
    P_L_POS = IE_L_POS*XVAL;
    P_M_POS = IE_M_POS*XVAL;
    P_H_POS = IE_H_POS*XVAL;
   ",
   
   PLOT = "
    TYPE = plot2;
   ",
   OUTPUT = "
    cint;
    STDYX",
   rdata = df.raw)

mplusModeler(SEM.mod.SCD, modelout = "./OUTPUT/SEM/Mplus/SEM.mod.SCD.inp", run = 1L)
rm(SEM.mod.SCD)
```

```{r mutate UDSC}
df.clean <- df.raw %>%
  dplyr::mutate(UDSC = case_when(
    USC <= 4 & DSC <= 4 ~ 1,
    USC > 4 & DSC <= 4 ~ 2,
    USC <= 4 & DSC > 4 ~ 3,
    USC > 4 & DSC > 4 ~ 4
  ))
```
### USC & DSC as moderation
```{r Moderator is UDSC, include=FALSE}
SEM.mod.UDSC <- mplusObject(
   TITLE = "
    Moderator is UDSC;
   ",
   ANALYSIS = "
    TYPE =general RANDOM;  
    estimator=MLR; 
    ALGORITHM=INTEGRATION;
    convergence=0.01;
   ",
   MODEL = "  
    ASC by ASC1-ASC5;
    OSC by OSC1-OSC6;
    SCO by ASC@0.8 OSC@0.8;
    
    UDSC@1;
    OUD | SCO XWITH UDSC;
    
    RD by RD1-RD5;
    POS by POS1-POS5;
    
    LS by LS1-LS5;
    
    RD on SCO(a1)
          UDSC
          OUD(w1);
    POS on SCO(a2)
           UDSC
           OUD(w2);
    LS on SCO(c)
          RD(b1)
          POS(b2);
   ",
   MODELCONSTRAINT = "
   NEW(LULD HULD LUHD HUHD
      IE_LL_RD IE_HL_RD IE_LH_RD IE_HH_RD
      IE_LL_POS IE_HL_POS IE_LH_POS IE_HH_POS
      );
   
    LULD = 1;
    HULD = 2;
    LUHD = 3;
    HUHD = 4;
   
    IE_LL_RD = (a1+w1*LULD)*b1;
    IE_HL_RD = (a1+w1*HULD)*b1;
    IE_LH_RD = (a1+w1*LUHD)*b1;
    IE_HH_RD = (a1+w1*HUHD)*b1;
   
    IE_LL_POS = (a2+w2*LULD)*b2;
    IE_HL_POS = (a2+w2*HULD)*b2;
    IE_LH_POS = (a2+w2*LUHD)*b2;
    IE_HH_POS = (a2+w2*HUHD)*b2;
   
    PLOT(P_LL_RD P_HL_RD P_LH_RD P_HH_RD
         P_LL_POS P_HL_POS P_LH_POS P_HH_POS);
    LOOP(XVAL,1,7,0.1);
    P_LL_RD = IE_LL_RD*XVAL;
    P_HL_RD = IE_HL_RD*XVAL;
    P_LH_RD = IE_LH_RD*XVAL;
    P_HH_RD = IE_HH_RD*XVAL;

    P_LL_POS = IE_LL_POS*XVAL;
    P_HL_POS = IE_HL_POS*XVAL;
    P_LH_POS = IE_LH_POS*XVAL;
    P_HH_POS = IE_HH_POS*XVAL;
   ",
   
   PLOT = "
    TYPE = plot2;
   ",
   OUTPUT = "
    cint;
    STDYX",
   rdata = df.clean)

mplusModeler(SEM.mod.UDSC, modelout = "./OUTPUT/SEM/Mplus/SEM.mod.UDSC.inp", run = 1L)
rm(SEM.mod.UDSC)
```

```{r Moderator is USC_DSC, include=FALSE}
SEM.mod.USC_DSC <- mplusObject(
   TITLE = "
    Moderator is USC DSC;
   ",
   ANALYSIS = "
    TYPE =general RANDOM;  
    estimator=MLR; 
    ALGORITHM=INTEGRATION;
    convergence=0.01;
   ",
   MODEL = "  
    ASC by ASC1-ASC5;
    OSC by OSC1-OSC6;
    SCO by ASC@0.8 OSC@0.8;
    
    USC@1;
    DSC@1;
    SCOU | SCO XWITH USC;
    SCOD | SCO XWITH DSC;
    
    RD by RD1-RD5;
    POS by POS1-POS5;
    
    LS by LS1-LS5;
    
    RD on SCO(a1)
          USC
          SCOU(w1);
    POS on SCO(a2)
           DSC
           SCOD(w2);
    LS on SCO(c)
          RD(b1)
          POS(b2);
   ",
   MODELCONSTRAINT = "
   NEW(L_UDSC M_UDSC H_UDSC
      IE_L_RD IE_M_RD IE_H_RD
      IE_L_POS IE_M_POS IE_H_POS
      
      DIF_LM_RD DIF_LH_RD DIF_MH_RD
      DIF_LM_POS DIF_LH_POS DIF_MH_POS
      );
   
    L_UDSC = -1;
    M_UDSC = 0;
    H_UDSC = 1;
   
    IE_L_RD = (a1+w1*L_UDSC)*b1;
    IE_M_RD = (a1+w1*M_UDSC)*b1;
    IE_H_RD = (a1+w1*H_UDSC)*b1;
   
    IE_L_POS = (a2+w2*L_UDSC)*b2;
    IE_M_POS = (a2+w2*M_UDSC)*b2;
    IE_H_POS = (a2+w2*H_UDSC)*b2;
   
    DIF_LM_RD = IE_L_RD - IE_M_RD;
    DIF_LH_RD = IE_L_RD - IE_H_RD;
    DIF_MH_RD = IE_M_RD - IE_H_RD;
    
    DIF_LM_POS = IE_L_POS - IE_M_POS;
    DIF_LH_POS = IE_L_POS - IE_H_POS;
    DIF_MH_POS = IE_M_POS - IE_H_POS;
   
    PLOT(P_L_RD P_M_RD P_H_RD
         P_L_POS P_M_POS P_H_POS);
    LOOP(XVAL,1,7,0.1);
    P_L_RD = IE_L_RD*XVAL;
    P_M_RD = IE_M_RD*XVAL;
    P_H_RD = IE_H_RD*XVAL;
    
    P_L_POS = IE_L_POS*XVAL;
    P_M_POS = IE_M_POS*XVAL;
    P_H_POS = IE_H_POS*XVAL;
   ",
   
   PLOT = "
    TYPE = plot2;
   ",
   OUTPUT = "
    cint;
    STDYX",
   rdata = df.raw)

mplusModeler(SEM.mod.USC_DSC, modelout = "./OUTPUT/SEM/Mplus/SEM.mod.USC_DSC.inp", run = 1L)
rm(SEM.mod.USC_DSC)
```
### SCS as moderation
```{r Moderator is SCS, include=FALSE}
SEM.mod.SCS <- mplusObject(
   TITLE = "
    Moderator is SCS(UC DC);
   ",
   ANALYSIS = "
    TYPE =general RANDOM;  
    estimator=MLR; 
    ALGORITHM=INTEGRATION;
    convergence=0.01;
    process=16;
   ",
   MODEL = "  
    ASC by ASC1-ASC5;
    OSC by OSC1-OSC6;
    SCO by ASC@0.8 OSC@0.8;
    
    UC by UC1-UC3;
    UC@1;
    DC by DC1-DC3;
    DC@1;
    
    SCOUC | SCO XWITH UC;
    SCODC | SCO XWITH DC;
    
    RD by RD1-RD5;
    POS by POS1-POS5;
    
    LS by LS1-LS5;
    
    RD on SCO(a1)
          UC
          SCOUC(w1);
    POS on SCO(a2)
           DC
           SCODC(w2);
    LS on SCO(c)
          RD(b1)
          POS(b2);
   ",
   MODELCONSTRAINT = "
   NEW(L_SCS M_SCS H_SCS
       IE_L_RD IE_M_RD IE_H_RD
       IE_L_POS IE_M_POS IE_H_POS
      
       DIF_LM_RD DIF_LH_RD DIF_MH_RD
       DIF_LM_POS DIF_LH_POS DIF_MH_POS
      );
   
    L_SCS = -1;
    M_SCS = 0;
    H_SCS = 1;
   
    IE_L_RD = (a1+w1*L_SCS)*b1;
    IE_M_RD = (a1+w1*M_SCS)*b1;
    IE_H_RD = (a1+w1*H_SCS)*b1;
   
    IE_L_POS = (a2+w2*L_SCS)*b2;
    IE_M_POS = (a2+w2*M_SCS)*b2;
    IE_H_POS = (a2+w2*H_SCS)*b2;
   
    DIF_LM_RD = IE_L_RD - IE_M_RD;
    DIF_LH_RD = IE_L_RD - IE_H_RD;
    DIF_MH_RD = IE_M_RD - IE_H_RD;
    
    DIF_LM_POS = IE_L_POS - IE_M_POS;
    DIF_LH_POS = IE_L_POS - IE_H_POS;
    DIF_MH_POS = IE_M_POS - IE_H_POS;
   
    PLOT(P_L_RD P_M_RD P_H_RD
         P_L_POS P_M_POS P_H_POS);
    LOOP(XVAL,1,7,0.1);
    P_L_RD = IE_L_RD*XVAL;
    P_M_RD = IE_M_RD*XVAL;
    P_H_RD = IE_H_RD*XVAL;
    
    P_L_POS = IE_L_POS*XVAL;
    P_M_POS = IE_M_POS*XVAL;
    P_H_POS = IE_H_POS*XVAL;
   ",
   
   PLOT = "
    TYPE = plot2;
   ",
   OUTPUT = "
    cint;
    STDYX",
   rdata = df.raw)

mplusModeler(SEM.mod.SCS, modelout = "./OUTPUT/SEM/Mplus/SEM.mod.SCS.inp", run = 1L)
rm(SEM.mod.SCS)
```