# Structural Equation Modeling
## Mediation
```{r Mediation SEM}
result.SEM.med <- capture.output({
  SEM.med <- '
    RD =~ RD1 + RD2 + RD3 + RD4 + RD5
    POS =~ POS1 + POS2 + POS3 + POS5 + POS6
    LS =~ LS1 + LS2 + LS3 + LS4 + LS5
    
    RD =~ a1 * USC + DSC
    POS =~ a2 * DSC + USC
    LS =~ b1 * RD + b2 * POS + c1 * USC + c2 * DSC
  
    IE_RD := a1 * b1
    IE_POS := a2 * b2
  ' %>%
  lavaan::sem(
    .,data=df.raw, estimator="ML",
    se = "bootstrap", bootstrap = 5000,
    parallel = "snow", ncpus = 16, iseed = 123)
  lavaan::summary(SEM.med, fit.measures=TRUE, standardized=TRUE)
})

writeLines(result.SEM.med, "./OUTPUT/SEM/SEM.med.md")

rm(result.SEM.med)
```

```{r Mediation SEM Mplus}
SEM.med <- mplusObject(
   TITLE = "
    Mediation;
   ",
   ANALYSIS = "
    TYPE =general;
    bootstrap = 5000;
    process=16;
   ",
   MODEL = "  
    RD by RD1-RD5;
    POS by POS1-POS3 POS5 POS6;
    
    LS by LS1-LS5;
   
    RD on USC(a1)
          DSC;
    POS on USC
           DSC(a2);
    LS on USC(c1)
          DSC(c2)
          RD(b1)
          POS(b2);
   ",
   MODELCONSTRAINT = "
   NEW(IE_RD 
       IE_POS);
   
    IE_RD = a1*b1;
    IE_POS = a2*b2;
   ",
   OUTPUT = "
    CINT(bcbootstrap);
    STDYX",
   rdata = df.raw)

mplusModeler(SEM.med, modelout = "./OUTPUT/SEM/Mplus/SEM.med.inp", run = 1L)
rm(SEM.med)
```

## Moderation

### USC & DSC as moderation
```{r Moderator is USC_DSC, include=FALSE}
SEM.mod.USC_DSC <- mplusObject(
   TITLE = "
    Moderator is USC DSC;
   ",
   ANALYSIS = "
    TYPE =general;
    bootstrap = 5000;
    process=16;
   ",
   MODEL = "  
    ASC by ASC1-ASC5;
    OSC by OSC1-OSC4 OSC6 OSC7;
    SCO by ASC OSC;

    RD by RD1-RD5;
    POS by POS1-POS3 POS5 POS6;
    
    LS by LS1-LS5;
    
    RD on USC(a1)
          DSC
          SCO;
    POS on USC
           DSC(a2)
           SCO;
    LS on USC
          DSC
          SCO
          RD(b1)
          POS(b2);
   ",
   MODELCONSTRAINT = "
   NEW(IE_RD 
       IE_POS
       );
   
   
    IE_RD = a1*b1;
    IE_POS = a2*b2;
   ",
   
   PLOT = "
    TYPE = plot2;
   ",
   OUTPUT = "
    cint;
    STDYX",
   rdata = df.raw)

mplusModeler(SEM.mod.USC_DSC, modelout = "./OUTPUT/SEM/Mplus/SEM.mod.USC_DSC_BASE.inp", run = 1L)
rm(SEM.mod.USC_DSC)
```

```{r Moderator is USC_DSC, include=FALSE}
SEM.mod.USC_DSC <- mplusObject(
   TITLE = "
    Moderator is USC DSC;
   ",
   ANALYSIS = "
    TYPE =general RANDOM;  
    estimator=BAYES; 
    ALGORITHM=INTEGRATION;
    convergence=0.01;
   ",
   MODEL = "  
    ASC by ASC1-ASC5;
    OSC by OSC1-OSC4 OSC6 OSC7;
    SCO by ASC OSC;

    SCO@1; 
   
    SCOU | SCO XWITH USC;
    SCOD | SCO XWITH DSC;
    
    RD by RD1-RD5;
    POS by POS1-POS3 POS5 POS6;
    
    LS by LS1-LS5;
    
    RD on SCO
          USC(a1)
          DSC
          SCOU(w1)
          SCOD;
    POS on SCO
           USC
           DSC(a2)
           SCOU
           SCOD(w2);
    LS on USC
          DSC
          SCO
          RD(b1)
          POS(b2);
   ",
   MODELCONSTRAINT = "
   NEW(L_SCO M_SCO H_SCO
   
      IE_RD IE_POS
   
      IE_L_RD IE_M_RD IE_H_RD
      IE_L_POS IE_M_POS IE_H_POS

      DIF_LM_RD DIF_LH_RD DIF_MH_RD
      DIF_LM_POS DIF_LH_POS DIF_MH_POS
      );
   
    L_SCO = -1;
    M_SCO = 0;
    H_SCO = 1;
   
    IE_RD = a1*b1;
    IE_POS = a2*b2;
   
    IE_L_RD = (a1+w1*L_SCO)*b1;
    IE_M_RD = (a1+w1*M_SCO)*b1;
    IE_H_RD = (a1+w1*H_SCO)*b1;
   
    IE_L_POS = (a2+w2*L_SCO)*b2;
    IE_M_POS = (a2+w2*M_SCO)*b2;
    IE_H_POS = (a2+w2*H_SCO)*b2;
   
    DIF_LM_RD = IE_L_RD - IE_M_RD;
    DIF_LH_RD = IE_L_RD - IE_H_RD;
    DIF_MH_RD = IE_M_RD - IE_H_RD;
    
    DIF_LM_POS = IE_L_POS - IE_M_POS;
    DIF_LH_POS = IE_L_POS - IE_H_POS;
    DIF_MH_POS = IE_M_POS - IE_H_POS;
   
    PLOT(P_L_RD P_M_RD P_H_RD
         P_L_POS P_M_POS P_H_POS);
    LOOP(XVAL,1,7,0.1);
    P_L_RD = IE_L_RD*XVAL;
    P_M_RD = IE_M_RD*XVAL;
    P_H_RD = IE_H_RD*XVAL;
    
    P_L_POS = IE_L_POS*XVAL;
    P_M_POS = IE_M_POS*XVAL;
    P_H_POS = IE_H_POS*XVAL;
   ",
   
   PLOT = "
    TYPE = plot2;
   ",
   OUTPUT = "
    cint;
    STDYX",
   rdata = df.raw)

mplusModeler(SEM.mod.USC_DSC, modelout = "./OUTPUT/SEM/Mplus/SEM.mod.USC_DSC.inp", run = 1L)
rm(SEM.mod.USC_DSC)
```