---
title: "CFA"
author: "yuki"
date: "2023-08-10"
output: html_document
---
# Confirmatory Factor Analysis
```{r CFA: RD}
yukiCFA(
  data = df.raw,
  model = "RD =~ RD1 + RD2 + RD3 + RD4 + RD5",
  path = "./OUTPUT/CFA/RD.md"
)
```

```{r CFA: POS}
yukiCFA(
  data = df.raw,
  model = "POS =~ POS1 + POS2 + POS3 + POS5 + POS6",
  path = "./OUTPUT/CFA/POS.md"
)
```

```{r CFA: POS}
yukiCFA(
  data = df.raw,
  model = "LS =~ LS1 + LS2 + LS3 + LS4 + LS5",
  path = "./OUTPUT/CFA/LS.md"
)
```

```{r CFA}
yukiCFA(
  data = df.raw,
  model = "
    RD =~ RD1 + RD2 + RD3 + RD4 + RD5
    POS =~ POS1 + POS2 + POS3 + POS5 + POS6
    LS =~ LS1 + LS2 + LS3 + LS4 + LS5
  ",
  path = "./OUTPUT/CFA/CFA.md"
)
```

```{r matrix.CFA}
CFA <- "
    SC =~ 0.9*SCD
    RD =~ RD1 + RD2 + RD3 + RD4 + RD5
    POS =~ POS1 + POS2 + POS3 + POS5 + POS6
    LS =~ LS1 + LS2 + LS3 + LS4 + LS5
  " %>%
  lavaan::cfa(.,data = df.raw, estimator="MLR") 
  lavaan::summary(CFA, fit.measures=TRUE, standardized=TRUE)

matrix.CFA <- lavaan::lavInspect(CFA,"standardized") 
CFA.loading <- as.data.frame(matrix.CFA$lambda) %>%
  dplyr::select(SC, RD, POS, LS) %>%
  dplyr::mutate_at(vars(SC, RD, POS, LS), round, 3)
CFA.loading[CFA.loading == 0] <- NA

CFA.correlation <- as.data.frame(matrix.CFA$psi) %>%
  dplyr::mutate_at(vars(SC, RD, POS, LS), round, 3) %>%
  .[c("SC", "RD", "POS", "LS"), c("SC", "RD", "POS", "LS")]

write.csv(CFA.loading, "./OUTPUT/CFA/loading.csv")
write.csv(CFA.correlation, "./OUTPUT/CFA/latent_correlation.csv")

rm(CFA, matrix.CFA)
```
